import type { Provider } from '@angular/core';
import {
    LucideActivity,
    LucideBell,
    LucideBold,
    LucideBookmark,
    LucideBriefcase,
    LucideBuilding2,
    LucideCalendar,
    LucideCheck,
    LucideChevronDown,
    LucideChevronLeft,
    LucideChevronRight,
    LucideChevronsUpDown,
    LucideCircleAlert,
    LucideCircleDollarSign,
    LucideContactRound,
    LucideEllipsisVertical,
    LucideEye,
    LucideHeading2,
    LucideItalic,
    LucideLayoutDashboard,
    LucideLink,
    LucideList,
    LucideListOrdered,
    LucideLogOut,
    LucideMenu,
    LucideMoon,
    LucidePanelLeft,
    LucidePin,
    LucidePlus,
    LucideRemoveFormatting,
    LucideSearch,
    LucideSettings,
    LucideShield,
    LucideStickyNote,
    LucideSun,
    LucideTag,
    LucideTrash2,
    LucideUnderline,
    LucideUser,
    LucideUsers,
    LucideX,
    provideLucideConfig,
    provideLucideIcons,
} from '@lucide/angular';

/** Kebab-case icon names registered for the app. */
export const APP_ICON_NAMES = [
    'layout-dashboard',
    'users',
    'shield',
    'settings',
    'log-out',
    'menu',
    'x',
    'chevron-down',
    'chevron-right',
    'bell',
    'search',
    'plus',
    'activity',
    'user',
    'check',
    'alert-circle',
    'panel-left',
    'chevrons-up-down',
    'more-vertical',
    'sun',
    'moon',
    'trash-2',
    'eye',
    'contact-round',
    'briefcase',
    'building-2',
    'calendar',
    'chevron-left',
    'circle-dollar-sign',
    'list',
    'tag',
    'bookmark',
    'sticky-note',
    'bold',
    'italic',
    'underline',
    'list-ordered',
    'link',
    'pin',
    'heading-2',
    'remove-format',
] as const;

export type IconName = (typeof APP_ICON_NAMES)[number];

const APP_LUCIDE_ICONS = [
    LucideLayoutDashboard,
    LucideUsers,
    LucideShield,
    LucideSettings,
    LucideLogOut,
    LucideMenu,
    LucideX,
    LucideChevronDown,
    LucideChevronLeft,
    LucideChevronRight,
    LucideBell,
    LucideBookmark,
    LucideSearch,
    LucidePlus,
    LucideActivity,
    LucideUser,
    LucideCheck,
    LucideCircleAlert,
    LucidePanelLeft,
    LucideChevronsUpDown,
    LucideEllipsisVertical,
    LucideSun,
    LucideMoon,
    LucideTrash2,
    LucideEye,
    LucideContactRound,
    LucideBriefcase,
    LucideBuilding2,
    LucideCalendar,
    LucideCircleDollarSign,
    LucideList,
    LucideTag,
    LucideStickyNote,
    LucideBold,
    LucideItalic,
    LucideUnderline,
    LucideListOrdered,
    LucideLink,
    LucidePin,
    LucideHeading2,
    LucideRemoveFormatting,
] as const;

/** Registers all app icons for dynamic `lucideIcon` usage by name. */
export function provideAppIcons(): Provider {
    return provideLucideIcons(...APP_LUCIDE_ICONS);
}

/** Global Lucide defaults (overridable per icon via inputs). */
export function provideAppIconConfig(): Provider {
    return provideLucideConfig({
        size: 16,
        strokeWidth: 2,
    });
}
