/**
 * Writes build-env.ts from API_BASE_URL (Vercel / CI).
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const apiBaseUrl = (process.env.API_BASE_URL ?? '/api/v1').trim().replace(/\/$/, '') || '/api/v1';
const normalized = apiBaseUrl.endsWith('/api/v1') ? apiBaseUrl : `${apiBaseUrl}/api/v1`;

const content = `/** Auto-generated by scripts/set-env.mjs — do not edit manually */\nexport const buildApiBaseUrl = '${normalized.replace(/'/g, "\\'")}';\n`;

writeFileSync(join(__dirname, '../src/environments/build-env.ts'), content, 'utf8');
console.log(`[set-env] apiBaseUrl = ${normalized}`);
