import { Router } from "express";
import { authRouter } from "./modules/auth/auth.routes";
import { dashboardRouter } from "./modules/dashboard/dashboard.routes";
import { healthRouter } from "./modules/health/health.routes";
import { roleRouter } from "./modules/roles/role.routes";
import { sessionRouter } from "./modules/sessions/session.routes";
import { userRouter } from "./modules/users/user.routes";
import { contactRouter } from "./modules/contacts/contact.routes";
import { dealRouter } from "./modules/deals/deal.routes";
import { activityRouter } from "./modules/activities/activity.routes";
import { companyRouter } from "./modules/companies/company.routes";
import { tagRouter } from "./modules/tags/tag.routes";
import { searchRouter } from "./modules/search/search.routes";
import { savedViewRouter } from "./modules/saved-views/saved-view.routes";
import { organizationRouter } from "./modules/organizations/organization.routes";
import { quoteRouter } from "./modules/quotes/quote.routes";
import { forecastRouter } from "./modules/forecasting/forecast.routes";
import { leadScoreRouter } from "./modules/lead-scoring/lead-score.routes";
import { calendarRouter } from "./modules/calendar/calendar.routes";
import { campaignRouter } from "./modules/campaigns/campaign.routes";
import { caseRouter } from "./modules/cases/case.routes";
import { knowledgeRouter } from "./modules/knowledge/knowledge.routes";
import { reportRouter } from "./modules/reports/report.routes";
import { workflowRouter } from "./modules/workflows/workflow.routes";
import { webhookRouter } from "./modules/webhooks/webhook.routes";
import { aiRouter } from "./modules/ai/ai.routes";
import { apiKeyRouter } from "./modules/api-keys/api-key.routes";
import { customFieldRouter } from "./modules/custom-fields/custom-field.routes";
import { territoryRouter } from "./modules/territories/territory.routes";
import { stickyNoteRouter } from "./modules/sticky-notes/sticky-note.routes";

export const router = Router();

router.use("/health", healthRouter);
router.use("/auth", authRouter);
router.use("/organizations", organizationRouter);
router.use("/dashboard", dashboardRouter);
router.use("/users", userRouter);
router.use("/sessions", sessionRouter);
router.use("/roles", roleRouter);
router.use("/contacts", contactRouter);
router.use("/deals", dealRouter);
router.use("/activities", activityRouter);
router.use("/companies", companyRouter);
router.use("/tags", tagRouter);
router.use("/search", searchRouter);
router.use("/saved-views", savedViewRouter);
router.use("/quotes", quoteRouter);
router.use("/forecasting", forecastRouter);
router.use("/lead-scoring", leadScoreRouter);
router.use("/calendar", calendarRouter);
router.use("/campaigns", campaignRouter);
router.use("/cases", caseRouter);
router.use("/knowledge", knowledgeRouter);
router.use("/reports", reportRouter);
router.use("/workflows", workflowRouter);
router.use("/webhooks", webhookRouter);
router.use("/ai", aiRouter);
router.use("/api-keys", apiKeyRouter);
router.use("/custom-fields", customFieldRouter);
router.use("/territories", territoryRouter);
router.use("/sticky-notes", stickyNoteRouter);
