import { Router } from "express";
import { analyticsRouter } from "./modules/analytics/analytics.routes";
import { authRouter } from "./modules/auth/auth.routes";
import { auditLogRouter } from "./modules/audit-logs/audit-log.routes";
import { brandRouter } from "./modules/brands/brand.routes";
import { categoryRouter } from "./modules/categories/category.routes";
import { cmsRouter } from "./modules/cms/cms.routes";
import { collectionRouter } from "./modules/collections/collection.routes";
import { couponRouter } from "./modules/coupons/coupon.routes";
import { customerRouter } from "./modules/customers/customer.routes";
import { giftCardRouter } from "./modules/gift-cards/gift-card.routes";
import { healthRouter } from "./modules/health/health.routes";
import { inventoryRouter } from "./modules/inventory/inventory.routes";
import { mediaRouter } from "./modules/media/media.routes";
import { notificationRouter } from "./modules/notifications/notification.routes";
import { orderRouter } from "./modules/orders/order.routes";
import { paymentRouter } from "./modules/payments/payment.routes";
import { permissionRouter } from "./modules/permissions/permission.routes";
import { productRouter } from "./modules/products/product.routes";
import { promotionRouter } from "./modules/promotions/promotion.routes";
import { purchaseOrderRouter } from "./modules/purchase-orders/purchase-order.routes";
import { refundRouter } from "./modules/refunds/refund.routes";
import { reportRouter } from "./modules/reports/report.routes";
import { reviewRouter } from "./modules/reviews/review.routes";
import { roleRouter } from "./modules/roles/role.routes";
import { sessionRouter } from "./modules/sessions/session.routes";
import { settingsRouter } from "./modules/settings/settings.routes";
import { supplierRouter } from "./modules/suppliers/supplier.routes";
import { userRouter } from "./modules/users/user.routes";
import { warehouseRouter } from "./modules/warehouses/warehouse.routes";

export const router = Router();

router.use("/health", healthRouter);
router.use("/auth", authRouter);
router.use("/users", userRouter);
router.use("/sessions", sessionRouter);
router.use("/roles", roleRouter);
router.use("/permissions", permissionRouter);
router.use("/audit-logs", auditLogRouter);
router.use("/products", productRouter);
router.use("/categories", categoryRouter);
router.use("/brands", brandRouter);
router.use("/collections", collectionRouter);
router.use("/warehouses", warehouseRouter);
router.use("/inventory", inventoryRouter);
router.use("/suppliers", supplierRouter);
router.use("/purchase-orders", purchaseOrderRouter);
router.use("/customers", customerRouter);
router.use("/orders", orderRouter);
router.use("/payments", paymentRouter);
router.use("/refunds", refundRouter);
router.use("/settings", settingsRouter);
router.use("/analytics", analyticsRouter);
router.use("/promotions", promotionRouter);
router.use("/coupons", couponRouter);
router.use("/gift-cards", giftCardRouter);
router.use("/reviews", reviewRouter);
router.use("/cms", cmsRouter);
router.use("/media", mediaRouter);
router.use("/notifications", notificationRouter);
router.use("/reports", reportRouter);
