-- Add product image audit actions
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_IMAGE_ADDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_IMAGE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_IMAGE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_IMAGES_REORDERED';
